---

- name: Criando estrutura de diretorios
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_real_group_id }}"
    mode: 0775
    recurse: yes
  with_items:
    - "/home/{{ custom_home }}/devops/ansible/inventories"
    - "/home/{{ custom_home }}/devops/ansible/keys"
    - "/home/{{ custom_home }}/devops/ansible/logs"
    - "/home/{{ custom_home }}/devops/ansible/playbooks"
    - "/home/{{ custom_home }}/devops/ansible/roles"
  become: true
  tags:
    - directory
  

- name: Atualizando a propriedade roles_path em /etc/ansible/ansible.cfg
  lineinfile:
    path: /etc/ansible/ansible.cfg
    regexp: "roles_path"
    line: "roles_path    = /home/{{ custom_home }}/devops/ansible/roles"
    backrefs: yes
    state: present
  become: true
  tags:
    - config


- name: "Atualizando a propriedade log_path em '/etc/ansible/ansible.cfg'"
  lineinfile:
    path: /etc/ansible/ansible.cfg
    regexp: "log_path"
    line: "log_path = /home/{{ custom_home }}/devops/ansible/logs/ansible.log"
    backrefs: yes
    state: present
  become: true
  tags:
    - config


- name: "Atualizando a propriedade private_key_file em '/etc/ansible/ansible.cfg'"
  lineinfile:
    path: /etc/ansible/ansible.cfg
    regexp: "#private_key_file"
    line: "#private_key_file = /home/{{ custom_home }}/ansible/keys/key.pem"
    backrefs: yes
    state: present
  become: true
  tags:
    - config